version: '3'

services:
  restaurants.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-windows
    environment:
      SA_PASSWORD: "your_password"
      ACCEPT_EULA: "Y"
networks:
  default:
    external:
      name: nat
