using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurants.API.Models.Enums
{
    public enum LanguageEnum
    {
        [DisplayName("Afrikaans")] Afrikaans = 1,
		[DisplayName("Albanian")] Albanian,
		[DisplayName("Alsatian")] Alsatian,
		[DisplayName("Amharic")] Amharic,
		[DisplayName("Arabic")] Arabic,
		[DisplayName("Armenian")] Armenian,
		[DisplayName("Assamese")] Assamese,
		[DisplayName("Azerbaijani")] Azerbaijani,
		[DisplayName("Bangla")] Bangla,
		[DisplayName("Bashkir")] Bashkir,
		[DisplayName("Basque")] Basque,
		[DisplayName("Belarusian")] Belarusian,
		[DisplayName("Bosnian")] Bosnian,
		[DisplayName("Breton")] Breton,
		[DisplayName("Bulgarian")] Bulgarian, 
		[DisplayName("Burmese")] Burmese,
		[DisplayName("Catalan")] Catalan,
		[DisplayName("Central Kurdish")] Central_Kurdish,
		[DisplayName("Cherokee")] Cherokee,
		[DisplayName("Chinese")] Chinese,
		[DisplayName("Corsican")] Corsican,
		[DisplayName("Croatian")] Croatian,
		[DisplayName("Czech")] Czech,
		[DisplayName("Danish")] Danish,
		[DisplayName("Dari")] Dari,
		[DisplayName("Divehi")] Divehi,
		[DisplayName("Dutch")] Dutch,
		[DisplayName("Dzongkha")] Dzongkha,
		[DisplayName("English")] English,
		[DisplayName("Estonian")] Estonian,
		[DisplayName("Faroese")] Faroese,
		[DisplayName("Filipino")] Filipino,
		[DisplayName("Finnish")] Finnish,
		[DisplayName("French")] French,
		[DisplayName("Frisian")] Frisian,
		[DisplayName("Fulah")] Fulah,
		[DisplayName("Galician")] Galician,
		[DisplayName("Georgian")] Georgian,
		[DisplayName("German")] German,
		[DisplayName("Greek")] Greek, 
		[DisplayName("Greenlandic")] Greenlandic,
		[DisplayName("Gujarati")] Gujarati,
		[DisplayName("Hausa")] Hausa,
		[DisplayName("Hawaiian")] Hawaiian,
		[DisplayName("Hebrew")] Hebrew,
		[DisplayName("Hindi")] Hindi,
		[DisplayName("hungarian")] hungarian,
		[DisplayName("Icelandic")] Icelandic,
		[DisplayName("Igbo")] Igbo,
		[DisplayName("Inari Sami")] Inari_Sami,
		[DisplayName("Indonesian")] Indonesian,
		[DisplayName("Inuktitut")] Inuktitut,
		[DisplayName("Irish")] Irish,
		[DisplayName("isiXhosa")] isiXhosa,
		[DisplayName("isiZulu")] isiZulu,
		[DisplayName("Italian")] Italian,
		[DisplayName("Japanese")] Japanese,
		[DisplayName("K'iche'")] K_iche,
		[DisplayName("Kannada")] Kannada,
		[DisplayName("Kazakh")] Kazakh,
		[DisplayName("Khmer")] Khmer,
		[DisplayName("Kinyarwanda")] Kinyarwanda,
		[DisplayName("Kiswahili")] Kiswahili,
		[DisplayName("Konkani")] Konkani,
		[DisplayName("Korean")] Korean,
		[DisplayName("Kyrgyz")] Kyrgyz,
		[DisplayName("Lao")] Lao,
		[DisplayName("Latvian")] Latvian,
		[DisplayName("Lithuanian")] Lithuanian,
		[DisplayName("Lower Sorbian")] Lower_Sorbian,
		[DisplayName("Lule Sami")] Lule_Sami,
		[DisplayName("Luxembourgish")] Luxembourgish,
		[DisplayName("Macedonian")] Macedonian, 
		[DisplayName("Malay")] Malay,
		[DisplayName("Malayalam")] Malayalam,
		[DisplayName("Maltese")] Maltese,
		[DisplayName("Maori")] Maori,
		[DisplayName("Mapundungun")] Mapundungun,
		[DisplayName("Marathi")] Marathi,
		[DisplayName("Mohawk")] Mohawk,
		[DisplayName("Mongolian")] Mongolian,
		[DisplayName("Nepali")] Nepali,
		[DisplayName("Northern Sami")] Northern_Sami,
		[DisplayName("Norwegian")] Norwegian,
		[DisplayName("Occitan")] Occitan,
		[DisplayName("Odia")] Odia,
		[DisplayName("Pashto")] Pashto,
		[DisplayName("Persian")] Persian,
		[DisplayName("Polish")] Polish,
		[DisplayName("Portuguese")] Portuguese,
		[DisplayName("Punjabi")] Punjabi,
		[DisplayName("Quechua")] Quechua,
		[DisplayName("Romanian")] Romanian,
		[DisplayName("Pomansh")] Pomansh,
		[DisplayName("Russian")] Russian,
		[DisplayName("Sakha")] Sakha,
		[DisplayName("Sanskrit")] Sanskrit,
		[DisplayName("Scottish Gaelic")] Scottish_Gaelic,
		[DisplayName("Serbian")] Serbian,
		[DisplayName("Sesotho sa Leboa")] Sesotho_sa_Leboa,
		[DisplayName("Setswana")] Setswana,
		[DisplayName("Sindhi")] Sindhi,
		[DisplayName("Sinhala")] Sinhala,
		[DisplayName("Skolt Sami")] Skolt_Sami,
		[DisplayName("Slovak")] Slovak,
		[DisplayName("Slovenian")] Slovenian,
		[DisplayName("Southern Sami")] Southern_Sami,
		[DisplayName("Spanish")] Spanish,
		[DisplayName("Standard Moroccan Tamazight")] Standard_Moroccan_Tamazight,
		[DisplayName("Swedish")] Swedish,
		[DisplayName("Syriac")] Syriac,
		[DisplayName("Tajik")] Tajik,
		[DisplayName("Tamil")] Tamil,
		[DisplayName("Tatar")] Tatar,
		[DisplayName("Telugu")] Telugu,
		[DisplayName("Thai")] Thai,
		[DisplayName("Tubetan")] Tubetan,
		[DisplayName("Tigrinya")] Tigrinya,
		[DisplayName("Turkish")] Turkish,
		[DisplayName("Turnmen")] Turnmen,
		[DisplayName("Ukrainian")] Ukrainian,
		[DisplayName("Upper Sorbian")] Upper_Sorbian,
		[DisplayName("Urdu")] Urdu,
		[DisplayName("Uyughur")] Uyughur,
		[DisplayName("Uzbek")] Uzbek,
		[DisplayName("Valencian")] Valencian,
		[DisplayName("Vietnamese")] Vietnamese,
		[DisplayName("Welsh")] Welsh,
		[DisplayName("Wolof")] Wolof,
		[DisplayName("Yi")] Yi,
		[DisplayName("Yoruba")] Yoruba
	}
}
